---
- hosts: localhost
  tasks:
    - name: Updating all packages
      apt:
        name: '*'
        state: latest
      become: true
    - name: Install Basic Packages
      apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      with_items:
        - openssh-server
        - htop
        - nmap
        - net-tools
        - rsyslog
        - zsh
        - speedtest-cli
        - terminator
        - code
        - rdesktop
        - smartmontools
        - dirmngr
        - apt-transport-https
        - curl
        - gnupg2
        - sysstat
        - iptraf-ng
        - jq
        - iotop
        - wget
        - git
        - dos2unix
      become: true
